core/urls.py
from django.urls import path, include
from core.views import *

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("profile/<username>/", ProfileView.as_view(), name="profile"),
    path("profile/edit/<username>/", ProfileEditView.as_view(), name="profile-edit"),
    path("users/", UserManagement.as_view(), name="user-management"),
    path(
        "users/edit/<username>/",
        EditUserManagent.as_view(),
        name="edit-user-management",
    ),
    path("download_product_csv", download_product_csv, name="product-download-csv"),
    # path('chalan/', ChalanCreateView.as_view(), name='chalan'),
    # path('chalan/<int:pk>/', ChalanDetailView.as_view(), name='chalan-detail'),
    # path('chalan-edit/<int:pk>/', ChalanUpdateView.as_view(), name='chalan-edit'),
    # path('chalan-delete/<int:pk>/', ChalanDeleteView.as_view(), name='chalan-delete'),
    path("product/", ProductView.as_view(), name="product"),
    path("product/create/", ProductCreateView.as_view(), name="product-create"),
    path("product/edit/<pk>/", ProductUpdateView.as_view(), name="product-edit"),
    path("product/delete/<pk>/", ProductDeleteView.as_view(), name="product-delete"),
    path("category/", CategoryCreateView.as_view(), name="category"),
    path("category/<pk>/", CategoryUpdateView.as_view(), name="category-edit"),
    path("category/delete/<pk>/", CategoryDeleteView.as_view(), name="category-delete"),
    path("sub-category/", SubCategoryCreateView.as_view(), name="subcategory"),
    path(
        "sub-category/<pk>/", SubCategoryUpdateView.as_view(), name="subcategory-edit"
    ),
    path(
        "sub-category/delete/<pk>/",
        SubCategoryDeleteView.as_view(),
        name="subcategory-delete",
    ),
    path("warehouse/", WarehouseCreateView.as_view(), name="warehouse"),
    path("warehouse/<pk>", WarehouseUpdateView.as_view(), name="warehouse-edit"),
    path(
        "warehouse/delete/<pk>", WarehouseDeleteView.as_view(), name="warehouse-delete"
    ),
]

inventory/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("api/v1/", include("core.api.urls", namespace="core_api")),
    path("api/v1/", include("purchase.api.urls", namespace="purchase_api")),
    path("api/v1/", include("sell.api.urls", namespace="sell_api")),
    path("", include("core.urls", namespace="core")),
    path("", include("purchase.urls", namespace="purchase")),
    path("", include("sell.urls", namespace="sell")),
    path("", include("order.urls", namespace="order")),
]

admin.site.site_header = "Inventory Admin Panel"
admin.site.index_title = "Inventory management"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path, include
from .views import *

app_name = "order"

urlpatterns = [
    # path("orders/", AllOrdersView.as_view(), name="all-orders"),
    path("order-list/", OrderListView.as_view(), name="order-list"),
    path(
        "order-create/<int:product_id>/", OrderCreateView.as_view(), name="order-create"
    ),
    path("order-edit/<int:pk>/", OrderUpdateView.as_view(), name="order-edit"),
    path("order-delete/<int:pk>/", OrderDeleteView.as_view(), name="order-delete"),
    path("order-sell/<int:pk>/", SellOrderItem.as_view(), name="sell-order"),
]

purchase/urls.py
from django.urls import path, include
from .views import *

app_name = "purchase"

urlpatterns = [
    path("purchase/invoice/<int:pk>/", purchaes_invoice, name="purchase-invoice"),
    path("purchase/create/", CreatePurchaseView.as_view(), name="purchase-create"),
    path(
        "purchase/edit/<pk>/", PurchaseProductUpdateView.as_view(), name="purchase-edit"
    ),
    path(
        "purchase/delete/<pk>/",
        PurchaseProductDeleteView.as_view(),
        name="purchase-delete",
    ),
    path("purchase/product/", PurchaseProductList.as_view(), name="product"),
]

sell/urls.py
from django.urls import path, include
from .views import *

app_name = "sell"

urlpatterns = [
    path("customer/", CustomerCreateView.as_view(), name="customer"),
    path("customer/<int:pk>/", SingleCustomerView.as_view(), name="single-customer"),
    path("customer/edit/<int:pk>/", CustomerUpdateView.as_view(), name="customer-edit"),
    path(
        "customer/delete/<int:pk>/",
        CustomerDeleteView.as_view(),
        name="customer-delete",
    ),
    path("sale/create/", SellProductCreateView.as_view(), name="sale-create"),
    path("sale/edit/<pk>/", SellProductUpdateView.as_view(), name="sale-edit"),
    path("sale/delete/<pk>/", SellProductDeleteView.as_view(), name="sale-delete"),
    path("sales/", SellProductListView.as_view(), name="sales"),
]

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
		<div class="alert alert-sm alert-{{message.tags}} alert-dismissible fade show" role="alert">
			{{ message }}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
    {% endfor %}
{% endif %}

templates/includes/sidebar.html
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'core:home' %}">
        <div class="sidebar-brand-icon">
            <i class="far fa-building"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Inventory</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:home' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    {% if user.is_staff or user.is_customer %}

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#order" aria-expanded="true"
            aria-controls="order">
            <i class="fa fa-file-invoice"></i>
            <span>Oeders</span>
        </a>
        <div id="order" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'order:order-list' %}">Orders</a>
            </div>
        </div>
    </li>

    {% if not user.is_customer and user.is_staff or user.is_superuser %}

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#products" aria-expanded="true"
            aria-controls="products">
            <i class="fas fa-fw fa-boxes"></i>
            <span>Products</span>
        </a>
        <div id="products" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'core:product-create' %}">Add Products</a>
                <a class="collapse-item" href="{% url 'core:product' %}">Products</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#sales" aria-expanded="true"
            aria-controls="sales">
            <i class="fas fa-fw fa-dollar-sign"></i>
            <span>Sales</span>
        </a>
        <div id="sales" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'sell:sale-create' %}">New Sale</a>
                <a class="collapse-item" href="{% url 'sell:sales' %}">Sales</a>
                <a class="collapse-item" href="{% url 'sell:customer' %}">Customers</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#purchases" aria-expanded="true"
            aria-controls="purchases">
            {% comment %} <i class="fas fa-fw fa-dolly-flatbed"></i> {% endcomment %}
            <i class="fas fa-fw fa-money-check-alt"></i>
            <span>Purchases</span>
        </a>
        <div id="purchases" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'purchase:purchase-create' %}">New Purchase</a>
                <a class="collapse-item" href="{% url 'purchase:product' %}">Purchases</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Pages Collapse Menu -->

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#catalog" aria-expanded="true"
            aria-controls="catalog">
            <i class="fas fa-fw fa-book"></i>
            <span>Catalog</span>
        </a>
        <div id="catalog" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'core:category' %}">Category</a>
                <a class="collapse-item" href="{% url 'core:subcategory' %}">Sub Category</a>
                <a class="collapse-item" href="{% url 'core:warehouse' %}">Warehouses</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#settings" aria-expanded="true"
            aria-controls="settings">
            <i class="fas fa-fw fa-cogs"></i>
            <span>Settings</span>
        </a>
        <div id="settings" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'core:user-management' %}">User Management</a>
            </div>
        </div>
    </li>

    {% endif %}

    {% endif %}

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>

templates/includes/topbar.html
{% load static %}

<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form
        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        {% comment %} <div class="topbar-divider d-none d-sm-block"></div> {% endcomment %}

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                <img class="img-profile rounded-circle"
                    src="{% static 'img/undraw_profile.svg' %}">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'core:profile' user.username %}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>

    </ul>

</nav>