core/urls.py
from django.urls import path, include
from core.views import *

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("profile/<username>/", ProfileView.as_view(), name="profile"),
    path("profile/edit/<username>/", ProfileEditView.as_view(), name="profile-edit"),
    path("users/", UserManagement.as_view(), name="user-management"),
    path(
        "users/edit/<username>/",
        EditUserManagent.as_view(),
        name="edit-user-management",
    ),
    path("download_product_csv", download_product_csv, name="product-download-csv"),
    # path('chalan/', ChalanCreateView.as_view(), name='chalan'),
    # path('chalan/<int:pk>/', ChalanDetailView.as_view(), name='chalan-detail'),
    # path('chalan-edit/<int:pk>/', ChalanUpdateView.as_view(), name='chalan-edit'),
    # path('chalan-delete/<int:pk>/', ChalanDeleteView.as_view(), name='chalan-delete'),
    path("product/", ProductView.as_view(), name="product"),
    path("product/create/", ProductCreateView.as_view(), name="product-create"),
    path("product/edit/<pk>/", ProductUpdateView.as_view(), name="product-edit"),
    path("product/delete/<pk>/", ProductDeleteView.as_view(), name="product-delete"),
    path("category/", CategoryCreateView.as_view(), name="category"),
    path("category/<pk>/", CategoryUpdateView.as_view(), name="category-edit"),
    path("category/delete/<pk>/", CategoryDeleteView.as_view(), name="category-delete"),
    path("sub-category/", SubCategoryCreateView.as_view(), name="subcategory"),
    path(
        "sub-category/<pk>/", SubCategoryUpdateView.as_view(), name="subcategory-edit"
    ),
    path(
        "sub-category/delete/<pk>/",
        SubCategoryDeleteView.as_view(),
        name="subcategory-delete",
    ),
    path("warehouse/", WarehouseCreateView.as_view(), name="warehouse"),
    path("warehouse/<pk>", WarehouseUpdateView.as_view(), name="warehouse-edit"),
    path(
        "warehouse/delete/<pk>", WarehouseDeleteView.as_view(), name="warehouse-delete"
    ),
]

inventory/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("api/v1/", include("core.api.urls", namespace="core_api")),
    path("api/v1/", include("purchase.api.urls", namespace="purchase_api")),
    path("api/v1/", include("sell.api.urls", namespace="sell_api")),
    path("", include("core.urls", namespace="core")),
    path("", include("purchase.urls", namespace="purchase")),
    path("", include("sell.urls", namespace="sell")),
    path("", include("order.urls", namespace="order")),
]

admin.site.site_header = "Inventory Admin Panel"
admin.site.index_title = "Inventory management"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path, include
from .views import *

app_name = "order"

urlpatterns = [
    # path("orders/", AllOrdersView.as_view(), name="all-orders"),
    path("order-list/", OrderListView.as_view(), name="order-list"),
    path(
        "order-create/<int:product_id>/", OrderCreateView.as_view(), name="order-create"
    ),
    path("order-edit/<int:pk>/", OrderUpdateView.as_view(), name="order-edit"),
    path("order-delete/<int:pk>/", OrderDeleteView.as_view(), name="order-delete"),
    path("order-sell/<int:pk>/", SellOrderItem.as_view(), name="sell-order"),
]

core/models.py
from unidecode import unidecode

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify

from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.validators import UnicodeUsernameValidator

from datetime import date
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile


class Organization(models.Model):
    name = models.CharField(max_length=100, unique=True)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=20, unique=True, blank=True, null=True)
    address = models.TextField()
    status = models.BooleanField(default=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class User(AbstractUser):
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_("first name"), max_length=30, blank=True)
    last_name = models.CharField(_("last name"), max_length=150, blank=True)
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, to_field="name", blank=True, null=True
    )
    email = models.EmailField(_("email address"), blank=True, unique=True)
    phone = models.CharField(max_length=11)
    is_customer = models.BooleanField(default=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    def __str__(self):
        return self.username


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True, max_length=100)
    status = models.BooleanField(default=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_update_url(self):
        return reverse("core:category-edit", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("core:category-delete", kwargs={"pk": self.pk})


class Subcategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True, max_length=100)
    status = models.BooleanField(default=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Subcategories"

    def __str__(self):
        return self.name

    def get_update_url(self):
        return reverse("core:subcategory-edit", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("core:subcategory-delete", kwargs={"pk": self.pk})


class Warehouse(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    status = models.BooleanField(default=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_update_url(self):
        return reverse("core:warehouse-edit", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("core:warehouse-delete", kwargs={"pk": self.pk})


class Product(models.Model):
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, blank=True, null=True
    )
    subcategory = models.ForeignKey(
        Subcategory, on_delete=models.SET_NULL, blank=True, null=True
    )
    warehouse = models.ForeignKey(
        Warehouse,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )

    product_name = models.CharField(max_length=100)
    product_slug = models.SlugField(blank=True, unique=True)
    sell_price = models.DecimalField(
        default=0, max_digits=8, decimal_places=2, blank=True, null=True
    )
    quantity = models.PositiveIntegerField(default=0, blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    status = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product_name

    def save(self, *args, **kwargs):
        self.product_slug = slugify(unidecode(self.product_name))
        super(Product, self).save(*args, **kwargs)

    def get_update_url(self):
        return reverse("core:product-edit", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("core:product-delete", kwargs={"pk": self.pk})

    @property
    def get_unique_number(self):
        product_name = str(self.product_name)
        _id = str(self.id)
        d = date.today()
        d = d.strftime("%d%m%y")

        unique_number = product_name[:2] + _id + "-" + d
        unique_number = unique_number.upper()

        return unique_number

templates/delete.html
{% extends './base.html' %}

{% block body %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="card shadow">
                        <div class="card-body">
                            <h1 class="h4 text-gray-700 mb-2">Are you sure to delete this item ?</h1>
                            <hr>
                            <h1 class="h5 text-gray-900 mb-2 text-center py-3">
                                <sup><i class="fa fa-quote-left text-secondary" aria-hidden="true"></i></sup>
                                {{ object }}
                                <sup><i class="fa fa-quote-right text-secondary" aria-hidden="true"></i></sup>
                            </h1>
                            <hr>

                            <div class="form-group">
                                <div class="d-flex justify-content-end">
                                    <button class="btn btn-outline-danger btn-sm" type="submit">Yes, Delete</button>
                                    <a href="{% url 'core:home' %}" class="btn ml-2 btn-primary btn-sm">No, Don't</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

templates/edit-user-management.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Manage User - {% endblock title %}

{% block body %}
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header">Edit User</div>
                <div class="card-body">
                    <form action="" method="POST" novalidate>
                        {% csrf_token %}

                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-6">
                                    {{ form.username|as_crispy_field }}
                                </div>
                                <div class="col-lg-6">
                                    {{ form.email|as_crispy_field }}
                                </div>
                                <div class="col-lg-6">
                                    {{ form.first_name|as_crispy_field }}
                                </div>
                                <div class="col-lg-6">
                                    {{ form.last_name|as_crispy_field }}
                                </div>
                                <div class="col-lg-6">
                                    {{ form.organization|as_crispy_field }}
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-lg-6">
                                    {{ form.is_active|as_crispy_field }}
                                </div>
                                <div class="col-lg-6">
                                    {{ form.is_staff|as_crispy_field }}
                                </div>
                            </div>
                        </div>

                        <div class="d-flex justify-content-end">
                            <a href="{% url 'core:user-management' %}" class="btn btn-secondary">Cancel</a>
                            <button class="btn btn-primary ml-2" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

templates/home.html
{% extends './base.html' %}

{% block title %}Dashboard - {% endblock title %}

{% block body %}

{% if not user.is_customer %}
<div class="row">
    <!-- Customers Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Customers</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ total_customer }}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-users fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Sales Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            Sells</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ total_sell }}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Products Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Products
                        </div>
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ total_products }}</div>
                            </div>
                            <div class="col">
                                <div class="progress progress-sm mr-2">
                                    <div class="progress-bar bg-info" role="progressbar" style="width: 50%"
                                        aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-fw fa-boxes fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Suppliers Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">
                            Orders</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ orders.count }}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fa fa-file-invoice fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}

<div class="row">
    <div class="col-lg-6">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Product List</h6>
            </div>
            <div class="card-body">

                {% comment %} <div class="d-flex justify-content-end">
                    <a class="btn btn-primary btn-sm mb-3" href="{% url 'core:product-download-csv' %}">Download CSV</a>
                </div> {% endcomment %}

                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Quantity</th>
                                <th>Sell Price</th>
                                {% if request.user.is_customer %}
                                <th>Action</th>
                                {% endif %}

                            </tr>
                        </thead>
                        <tbody>
                            {% for product in products %}
                            <tr>
                                {% comment %} <td>{{ product.chalan }}</td> {% endcomment %}
                                <td>{{ product.product_name }}</td>
                                <td>{{ product.quantity }}</td>
                                <td>{{ product.sell_price }}</td>


                                {% if request.user.is_customer %}
                                <td>
                                    <a class="btn btn-primary btn-sm"
                                        href="{% url 'order:order-create' product.pk %}">Order</a>
                                </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card mb-3 shadow">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Pending Orders</h6>
            </div>
            <div class="card-body">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

                    <thead>
                        <tr>
                            <th>Product</th>
                            <th>Quantity</th>
                            <th>Phone</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orders %}
                        <tr>
                            {% comment %} <td>{{ product.chalan }}</td> {% endcomment %}
                            <td>{{ order.product.product_name }}</td>
                            <td>{{ order.quantity }}</td>
                            <td>{{ order.user.phone }}</td>
                            <td><a href="" class="btn btn-primary">View</a></td>


                            {% if request.user.is_customer %}
                            <td>
                                <a class="btn btn-primary btn-sm"
                                    href="{% url 'order:order-create' product.pk %}">Order</a>
                            </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

templates/product_create.html
{% extends './base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}New Product - {% endblock title %}

{% block body %}
<main id="productCreate">
    <div class="row">
        <div class="col">
            <div class="card shadow mb-4">
                <div class="card-header">
                    <h6 class="m-0 font-weight-bold text-primary">{{title|title}}</h6>
                </div>
                <div class="card-body">
                    <div class="Product-form">
                        <form action="" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-4">
                                        {{form.warehouse|as_crispy_field}}
                                    </div>
                                    <div class="col-md-4">
                                        <label for="id_category" class="requiredField">Category</label>
                                        <select onchange="selectSubcategory()" id="id_category" name="category"
                                            class="select form-control">
                                            {% for value, name in form.category.field.choices %}
                                            <option value="{{ value }}"
                                                {% if value == form.category.value %}selected{% endif %}>{{ name }}
                                            </option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col-md-4">
                                        <label for="id_subcategory" class="">Subcategory</label>
                                        <select name="subcategory" class="select form-control" id="id_subcategory">
                                            {% for value, name in form.subcategory.field.choices %}
                                            <option value="{{ value }}"
                                                {% if value == form.subcategory.value %}selected{% endif %}>{{ name }}
                                            </option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        {{form.product_name|as_crispy_field}}
                                    </div>
                                    <div class="col-md-4">
                                        {{form.quantity|as_crispy_field}}
                                    </div>
                                    <div class="col-md-4">
                                        {{form.sell_price|as_crispy_field}}
                                    </div>
                                    <div class="col-md-6">
                                        {{form.description|as_crispy_field}}
                                    </div>
                                </div>
                            </div>
                            <div class="d-flex justify-content-end">
                                <button class="btn btn-secondary" type="reset">Reset</button>
                                <button class="btn btn-primary ml-2" type="submit">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock body %}



{% block extra_script %}
<script src="{% static 'js/core/product_create.js' %}"></script>
{% endblock extra_script %}

templates/profile-edit.html
{% extends './base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}


{% block title %}Profile - {% endblock title %}

{% block body %}
<div class="row justify-content-center">
    <div class="col-md-9">
        <div class="card shadow mb-4">
            <div class="card-header d-flex justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">@{{ user.username }}</h6>
                <h6 class="m-0 font-weight-bold"><a class="text-secondary" href="{% url 'core:profile' user.username %}">Cancel</a></h6>
            </div>
            <div class="card-body" width="30">
                <div class="table-responsive">
                    <form action="" method="post">
                        {% csrf_token %}
                        <table class="table table-borderless">
                            <tbody>
                                <tr>
                                    <th>First Name</th>
                                    <td>:</td>
                                    <td>{% crispy_field form.first_name %}</td>
                                </tr>
                                <tr>
                                    <th>Last Name</th>
                                    <td>:</td>
                                    <td>{% crispy_field form.last_name %}</td>
                                </tr>
                                <tr>
                                    <th>Organization</th>
                                    <td>:</td>
                                    <td>{{ object.organization }}</td>
                                </tr>
                                <tr>
                                    <th>Email Address</th>
                                    <td>:</td>
                                    <td>
                                        {{ object.email }} &nbsp; 
                                        <a href="{% url 'account_email' %}"><i class="fa fa-pen"></i></a>
                                    </td>
                                </tr>
                                <tr>
                                    <th>Phone Number</th>
                                    <td>:</td>
                                    <td>{% crispy_field form.phone %}</td>
                                </tr>
                                <tr>
                                    <th>Joining Date</th>
                                    <td>:</td>
                                    <td>{{ object.date_joined|date }}</td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-between">
                            <a href="{% url 'account_change_password' %}">Change Password</a>
                            <div class="">
                                <button type="reset" class="btn btn-secondary">Reset</button>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/profile.html
{% extends './base.html' %}
{% load crispy_forms_tags %}

{% block title %}Profile - {% endblock title %}

{% block body %}
<div class="row justify-content-center">
    <div class="col-md-9">
        <div class="card shadow mb-4">
            <div class="card-header d-flex justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">@{{ user.username }}</h6>
                <h6 class="m-0 font-weight-bold text-primary"><a href="{% url 'core:profile-edit' user.username %}">Edit Profile</a></h6>
            </div>
            <div class="card-body" width="30">
                <div class="table-responsive">
                    <table class="table table-borderless">
                        <tbody>
                            <tr>
                                <th>First Name</th>
                                <td>:</td>
                                <td>{{ object.first_name }}</td>
                            </tr>
                            <tr>
                                <th>Last Name</th>
                                <td>:</td>
                                <td>{{ object.last_name }}</td>
                            </tr>
                            <tr>
                                <th>Organization</th>
                                <td>:</td>
                                <td>{{ object.organization }}</td>
                            </tr>
                            <tr>
                                <th>Email Address</th>
                                <td>:</td>
                                <td>{{ object.email }} &nbsp;</td>
                            </tr>
                            <tr>
                                <th>Phone Number</th>
                                <td>:</td>
                                <td>{{ object.phone }}</td>
                            </tr>
                            <tr>
                                <th>Joining Date</th>
                                <td>:</td>
                                <td>{{ object.date_joined|date }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}