core/urls.py
from django.urls import path, include
from core.views import *

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("profile/<username>/", ProfileView.as_view(), name="profile"),
    path("profile/edit/<username>/", ProfileEditView.as_view(), name="profile-edit"),
    path("users/", UserManagement.as_view(), name="user-management"),
    path(
        "users/edit/<username>/",
        EditUserManagent.as_view(),
        name="edit-user-management",
    ),
    path("download_product_csv", download_product_csv, name="product-download-csv"),
    # path('chalan/', ChalanCreateView.as_view(), name='chalan'),
    # path('chalan/<int:pk>/', ChalanDetailView.as_view(), name='chalan-detail'),
    # path('chalan-edit/<int:pk>/', ChalanUpdateView.as_view(), name='chalan-edit'),
    # path('chalan-delete/<int:pk>/', ChalanDeleteView.as_view(), name='chalan-delete'),
    path("product/", ProductView.as_view(), name="product"),
    path("product/create/", ProductCreateView.as_view(), name="product-create"),
    path("product/edit/<pk>/", ProductUpdateView.as_view(), name="product-edit"),
    path("product/delete/<pk>/", ProductDeleteView.as_view(), name="product-delete"),
    path("category/", CategoryCreateView.as_view(), name="category"),
    path("category/<pk>/", CategoryUpdateView.as_view(), name="category-edit"),
    path("category/delete/<pk>/", CategoryDeleteView.as_view(), name="category-delete"),
    path("sub-category/", SubCategoryCreateView.as_view(), name="subcategory"),
    path(
        "sub-category/<pk>/", SubCategoryUpdateView.as_view(), name="subcategory-edit"
    ),
    path(
        "sub-category/delete/<pk>/",
        SubCategoryDeleteView.as_view(),
        name="subcategory-delete",
    ),
    path("warehouse/", WarehouseCreateView.as_view(), name="warehouse"),
    path("warehouse/<pk>", WarehouseUpdateView.as_view(), name="warehouse-edit"),
    path(
        "warehouse/delete/<pk>", WarehouseDeleteView.as_view(), name="warehouse-delete"
    ),
]

inventory/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("api/v1/", include("core.api.urls", namespace="core_api")),
    path("api/v1/", include("purchase.api.urls", namespace="purchase_api")),
    path("api/v1/", include("sell.api.urls", namespace="sell_api")),
    path("", include("core.urls", namespace="core")),
    path("", include("purchase.urls", namespace="purchase")),
    path("", include("sell.urls", namespace="sell")),
    path("", include("order.urls", namespace="order")),
]

admin.site.site_header = "Inventory Admin Panel"
admin.site.index_title = "Inventory management"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path, include
from .views import *

app_name = "order"

urlpatterns = [
    # path("orders/", AllOrdersView.as_view(), name="all-orders"),
    path("order-list/", OrderListView.as_view(), name="order-list"),
    path(
        "order-create/<int:product_id>/", OrderCreateView.as_view(), name="order-create"
    ),
    path("order-edit/<int:pk>/", OrderUpdateView.as_view(), name="order-edit"),
    path("order-delete/<int:pk>/", OrderDeleteView.as_view(), name="order-delete"),
    path("order-sell/<int:pk>/", SellOrderItem.as_view(), name="sell-order"),
]

order/models.py
from django.db import models
from core.models import Product, User
from django.urls import reverse


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    order_status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.product)

    @property
    def total_item_price(self):
        return self.product.sell_price * self.quantity

    def get_update_url(self):
        return reverse("order:order-edit", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("order:order-delete", kwargs={"pk": self.pk})

order/forms.py
from django import forms
from .models import *


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['quantity']

order/views.py
from django.http import request
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib import messages
from django.views.generic import View, ListView, UpdateView, DeleteView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin

from .models import *
from .forms import *

from core.models import Product
from sell.models import SellProduct, Customer
from sell.forms import SellProductForm, CustomerForm


# class AllOrdersView(LoginRequiredMixin,
#                     UserPassesTestMixin,
#                     ListView):
#     model = Order
#     template_name = 'order/order_list.html'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["title"] = 'Order List'
#         context["orders"] = Order.objects.all().order_by('order_status')
#         return context

#     def test_func(self):
#         if self.request.user.is_staff:
#             return True
#         return False


class OrderListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Order
    template_name = "order/order_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Order List"
        if self.request.user.is_customer:
            context["orders"] = Order.objects.filter(user=self.request.user).order_by(
                "order_status"
            )
        else:
            context["orders"] = Order.objects.all().order_by("order_status")
        return context

    def test_func(self):
        if self.request.user.is_customer or self.request.user.is_staff:
            return True
        return False


class OrderCreateView(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, *args, **kwargs):
        product = get_object_or_404(Product, pk=self.kwargs["product_id"])
        form = OrderForm(initial={"quantity": product.quantity})
        context = {
            "form": form,
            "product": product,
            "title": "Create New Order",
            "orders": Order.objects.filter(user=self.request.user),
        }
        return render(self.request, "order/create_order.html", context)

    def post(self, *args, **kwargs):
        form = OrderForm(self.request.POST or None)

        if form.is_valid():
            quantity = form.cleaned_data.get("quantity")
            product = get_object_or_404(Product, pk=self.kwargs["product_id"])
            new_order = Order(
                quantity=quantity, product=product, user=self.request.user
            )
            new_order.save()
            messages.success(self.request, "Order created successfully")
            return redirect("./")
        else:
            return redirect("./")

    def test_func(self):
        if self.request.user.is_customer:
            return True
        return False


class OrderUpdateView(
    LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView
):
    model = Order
    form_class = OrderForm
    template_name = "order/create_order.html"
    success_url = "order:order-list"
    success_message = "Order was updated successfully"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Edit Order"
        context["orders"] = Order.objects.filter(user=self.request.user)
        return context

    def get_success_url(self, **kwargs):
        return reverse(self.success_url)

    def test_func(self):
        if self.request.user.is_customer:
            return True
        return False


class OrderDeleteView(
    LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, DeleteView
):
    model = Order
    template_name = "delete.html"
    success_url = "order:order-list"
    success_message = "Order was deleted successfully"

    def get_success_url(self, **kwargs):
        return reverse(self.success_url)

    def test_func(self):
        if self.request.user.is_customer:
            current_user = self.get_object()
            if self.request.user == current_user.user:
                return True
        return False


class SellOrderItem(
    LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, CreateView
):
    model = SellProduct
    template_name = "order/order_sell.html"
    form_class = SellProductForm
    success_url = "sell:sales"
    success_message = "Order was created successfully"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["products"] = SellProduct.objects.all()
        return context

    def get_success_url(self, **kwargs):
        return reverse(self.success_url)

    def get(self, *args, **kwargs):
        order_instance = get_object_or_404(Order, pk=self.kwargs["pk"])
        customer = Customer.objects.get(phone=order_instance.user.phone)
        sale_item_form = SellProductForm(
            initial={
                "customer": customer,
                "product": order_instance.product,
                "price": order_instance.product.sell_price,
                "quantity": order_instance.quantity,
            }
        )

        context = {
            "sale_item_form": sale_item_form,
            "customer": customer,
        }
        return render(self.request, "order/order_sell.html", context)

    def post(self, *args, **kwargs):
        order_instance = get_object_or_404(Order, pk=self.kwargs["pk"])
        product_instance = get_object_or_404(Product, pk=order_instance.product.pk)

        sell_form = SellProductForm(self.request.POST)

        if sell_form.is_valid():
            quantity = sell_form.cleaned_data.get("quantity")

            if quantity <= product_instance.quantity:
                new_qntty = product_instance.quantity - quantity
                product_instance.quantity = new_qntty
            else:
                messages.error(self.request, "Insufficient product quantity")
                return redirect("./")

            sell_item = sell_form.save(commit=False)
            sell_item.added_by = self.request.user
            sell_item.save()
            product_instance.save(update_fields=["quantity"])

            order_instance.order_status = True
            order_instance.save()

            messages.success(self.request, "Order created successfully")
            return redirect("order:order-list")
        else:
            print(
                "sale_item_form",
                sell_form.errors,
            )

            messages.warning(self.request, "Invalid form data")
            return redirect("./")

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False

templates/order/create_order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Orders{% endblock title %}

{% block body %}

<main>
    <div class="row">
        <div class="col">
            <div class="card shadow mb-4">
                <div class="card-header">
                    <h6 class="m-0 font-weight-bold text-primary">{{title|title}}</h6>
                </div>
                <div class="card-body">
                    <div class="category-form">
                        <div class="row justify-content-center">
                            <div class="col-md-8">

                                {% if product %}

                                    <table class="table table-bordered">
                                        <tr>
                                            <th>Product Name</th>
                                            <td>{{product}}</td>
                                        </tr>
                                        <tr>
                                            <th>Price</th>
                                            <td>{{product.sell_price}}</td>
                                        </tr>
                                        <tr>
                                            <th>In stock</th>
                                            <td>{{product.quantity}}</td>
                                        </tr>
                                        <tr>
                                            <th>Description</th>
                                            <td>{{product.description}}</td>
                                        </tr>
                                    </table>

                                {% elif object %}

                                    <table class="table table-bordered">
                                        <tr>
                                            <th>Product Name</th>
                                            <td>{{object}}</td>
                                        </tr>
                                        <tr>
                                            <th>Price</th>
                                            <td>{{object.product.sell_price}}</td>
                                        </tr>
                                        <tr>
                                            <th>In stock</th>
                                            <td>{{object.product.quantity}}</td>
                                        </tr>
                                        <tr>
                                            <th>Description</th>
                                            <td>{{object.product.description}}</td>
                                        </tr>
                                    </table>

                                {% endif %}

                                <form action="" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <div class="row justify-content-end">
                                            <div class="col-md-6">
                                                {{ form.quantity|as_crispy_field }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="buttons-right">
                                        <button class="btn btn-primary" type="submit">Order</button>
                                        <a href="{% url 'order:order-list' %}" class="btn btn-secondary">Cancel</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card shadow mb-4">
                <div class="card-header">
                    <h6 class="m-0 font-weight-bold text-primary">Orders</h6>
                </div>
                <div class="card-body">
                    <div class="department-list">
                        <div class="table-responsive">
                            <table class="table" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Product Name</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                        <th>Total Price</th>
                                        <th>Order Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                        <tr>
                                            <td>{{ order.product }}</td>
                                            <td>{{ order.product.sell_price }}</td>
                                            <td>{{ order.quantity }}</td>
                                            <td>{{ order.total_item_price }}</td>
                                            <td>
                                                {% if order.status == True %}
                                                    <span class="badge badge-success">Done</span>
                                                {% else %}
                                                    <span class="badge badge-warning">Pending</span>
                                                {% endif %}
                                            </td>
                                            <td>
                                                <a href="{{ order.get_update_url }}" class="btn btn-sm btn-outline-primary"><i class="fa fa-edit"></i></a>
                                                <a href="{{ order.get_delete_url }}" class="btn btn-sm btn-outline-danger"><i class="fa fa-trash-alt"></i></a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock body %}

templates/order/order_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Orders{% endblock title %}

{% block body %}

<main>
    <div class="row">
        <div class="col">
            <div class="card shadow mb-4">
                <div class="card-header">
                    <h6 class="m-0 font-weight-bold text-primary">{{title|title}}</h6>
                </div>
                <div class="card-body">
                    <div class="department-list">
                        <div class="table-responsive">
                            <table class="table" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Product Name</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                        <th>Total Price</th>
                                        <th>Order Status</th>

                                        {% if not request.user.is_customer %}
                                        <th>Customer Name</th>
                                        <th>Phone</th>
                                        {% endif %}

                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if request.user.is_customer %}

                                    {% for order in orders %}

                                    <tr>
                                        <td>{{ order.product }}</td>
                                        <td>{{ order.product.sell_price }}</td>
                                        <td>{{ order.quantity }}</td>
                                        <td>{{ order.total_item_price }}</td>
                                        <td>
                                            {% if order.order_status %}
                                            <span class="badge badge-success">Done</span>
                                            {% else %}
                                            <span class="badge badge-warning">Pending</span>
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a href="{{ order.get_update_url }}"
                                                class="btn btn-sm btn-outline-primary"><i class="fa fa-edit"></i></a>
                                            <a href="{{ order.get_delete_url }}"
                                                class="btn btn-sm btn-outline-danger"><i
                                                    class="fa fa-trash-alt"></i></a>
                                        </td>
                                    </tr>

                                    {% endfor %}

                                    {% endif  %}

                                    {% if request.user.is_staff %}

                                    {% for order in orders %}

                                    <tr>
                                        <td>{{ order.product }}</td>
                                        <td>{{ order.product.sell_price }}</td>
                                        <td>{{ order.quantity }}</td>
                                        <td>{{ order.total_item_price }}</td>
                                        <td>
                                            {% if order.order_status %}
                                            <span class="badge badge-success">Done</span>
                                            {% else %}
                                            <span class="badge badge-warning">Pending</span>
                                            {% endif %}
                                        </td>
                                        <td>{{ order.user.username }}</td>
                                        <td>{{ order.user.phone }}</td>
                                        <td>
                                            {% if not order.order_status %}
                                            <a href="{% url 'order:sell-order' order.pk %}"
                                                class="btn btn-sm btn-outline-primary">Sell</a>
                                            {% else %}
                                            <a href="" class="btn btn-sm btn-outline-primary">View</a>
                                            {% endif %}
                                        </td>
                                    </tr>

                                    {% endfor %}

                                    {% endif %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock body %}

templates/order/order_sell.html
{% extends '../base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Confirm Order - {% endblock title %}

{% block body %}
<main>
    <div class="row">
        <div class="col">
            <div class="card shadow mb-4">
                <div class="card-header">
                    <h6 class="m-0 font-weight-bold text-primary">Sale Order Item</h6>
                </div>
                <div class="card-body">
                    <form method="POST" action=".">
                        {% csrf_token %}
                        <div class="row">
                            <div class="d-none">
                                {{sale_form}}
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="">Customer Name</label>
                                    <input type="text" class="form-control" value="{{ customer.name }}" disabled>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="">Customer Phone</label>
                                    <input type="text" class="form-control" value="{{ customer.phone }}" disabled>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                {{ sale_item_form.product|as_crispy_field }}
                            </div>
                            <div class="col-md-4">
                                {{ sale_item_form.quantity|as_crispy_field }}
                            </div>
                            <div class="col-md-4">
                                {{ sale_item_form.price|as_crispy_field }}
                            </div>
                        </div>
                        <div class="d-flex justify-content-end mt-5">
                            <button type="reset" class="btn btn-secondary" type="submit">Reset</button>
                            <button class="btn btn-primary ml-2" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock body %}